#2.1 Data Manipulation

In [ ]:
import torch

Creating new tensor method : arange

In [ ]:
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

total number of elements in tensor method : numel

In [ ]:
x.numel()

12

the length along each axis
method : shape

In [ ]:
x.shape

torch.Size([12])

chage shape method : reshape

In [ ]:
X = x.reshape(3,4) # == x.reshape(-1,4) == x.reshape(3,-1)
X # 3*4 matrix

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [ ]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
torch.ones(2,3,4)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

element randomly and independently method : randn

In [ ]:
torch.randn(3,4) #들어가는건 dim

tensor([[ 1.7882, -0.3703, -0.8814,  0.0256],
        [ 0.4081, -2.9868, -0.6095,  0.9258],
        [-1.4957,  0.6718,  0.7990,  1.4699]])

construct tensors by supplying the exact values

In [ ]:
torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [ ]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [ ]:
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]), tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [ ]:
X[1,2] = 17
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 17.,  7.],
        [ 8.,  9., 10., 11.]])

In [ ]:
X[:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

Elementwise operation들 중 
mathematical operations

In [ ]:
torch.exp(X) #e^x에 x를 다 넣은거야

tensor([[162754.7969, 162754.7969, 162754.7969, 162754.7969],
        [162754.7969, 162754.7969, 162754.7969, 162754.7969],
        [  2980.9580,   8103.0840,  22026.4648,  59874.1406]])

In [ ]:
x = torch.tensor([1.0,2,4,8])
y = torch.tensor([2,2,2,2])
x+y, x-y, x*y, x**y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([ 1.,  4., 16., 64.]))

In [ ]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
torch.cat((X,Y),dim=0), torch.cat((X,Y),dim=1)
#dim=0은 axis 0을 기준으로, dim=1은 axis 1을 기준으로
#(3+3), (4+4) 꼴이 된거임

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [ ]:
X == Y #element check

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [ ]:
X < Y

tensor([[ True, False,  True, False],
        [False, False, False, False],
        [False, False, False, False]])

In [ ]:
X > Y

tensor([[False, False, False, False],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

In [ ]:
X.sum()

tensor(66.)

Broadcasting

In [ ]:
a = torch.arange(3).reshape((3,1))
b = torch.arange(3).reshape((1,3))
a, b

(tensor([[0],
         [1],
         [2]]), tensor([[0, 1, 2]]))

In [ ]:
a+b

tensor([[0, 1, 2],
        [1, 2, 3],
        [2, 3, 4]])

Saving Memory

In [ ]:
before = id(Y) # id method는 메모리 주소를 알려주는 연산자 in python
Y = Y+X
id(Y) == before #allocating new memory 사실을 알 수 있음

False

In [ ]:
Z = torch.zeros_like(Y)
print('id(Z):',id(Z))
Z[:] = X+Y #[:] = <expression>으로 in place update 가능
print('id(Z):',id(Z))

id(Z): 140435000235488
id(Z): 140435000235488


In [ ]:
before = id(X)
X += Y #+= 연산자도 in place update가 가능
id(X) == before

True

Conversino to Other Python Objects

In [ ]:
A = X.numpy()
B = torch.from_numpy(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [ ]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)
#item method는 텐서에서 파이썬 스칼라 형식으로 바꿔주구만 in size-1 tensor

(tensor([3.5000]), 3.5, 3.5, 3)

# 2.2 Data Preprocessing

Frist, Reading the dataset

In [1]:
import os

os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv') #우리가 사용할 데이터 파일
with open(data_file, 'w') as f:  #column이 아래
    f.write('''NumRooms,RoofType,Price  
NA,NA,127500
2,NA,106000
4,Slate,178100
NA,NA,140000''')

In [2]:
import pandas as pd

data = pd.read_csv(data_file)
print(data)

   NumRooms RoofType   Price
0       NaN      NaN  127500
1       2.0      NaN  106000
2       4.0    Slate  178100
3       NaN      NaN  140000


Data Preparation

In [5]:
inputs, targets = data.iloc[:, 0:2], data.iloc[:,2]
inputs = pd.get_dummies(inputs, dummy_na=True) #추정치로 바꾸는 것
print(inputs)

   NumRooms  RoofType_Slate  RoofType_nan
0       NaN               0             1
1       2.0               0             1
2       4.0               1             0
3       NaN               0             1


In [6]:
inputs = inputs.fillna(inputs.mean()) #남은 NaN을 mean으로 채우는거야
print(inputs)

   NumRooms  RoofType_Slate  RoofType_nan
0       3.0               0             1
1       2.0               0             1
2       4.0               1             0
3       3.0               0             1


Conversion to the tensor format

In [8]:
import torch

X, y = torch.tensor(inputs.values), torch.tensor(targets.values)
X, y

(tensor([[3., 0., 1.],
         [2., 0., 1.],
         [4., 1., 0.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500, 106000, 178100, 140000]))

# 2.3 Linear Algebra

In [2]:
import torch

x = torch.tensor(3.0)
y = torch.tensor(2.0)

x+y, x*y, x/y, x**y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

Vectors

In [3]:
x = torch.arange(3)
x

tensor([0, 1, 2])

In [4]:
x[2]

tensor(2)

In [5]:
len(x)

3

In [6]:
x.shape

torch.Size([3])

Matrices

In [8]:
A = torch.arange(6).reshape(3,2)
A

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [9]:
A.T #transpose

tensor([[0, 2, 4],
        [1, 3, 5]])

In [10]:
A = torch.tensor([[1,2,3],[2,0,4],[3,4,5]])
A == A.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

Tensors (high-order)

In [11]:
torch.arange(24).reshape(2,3,4)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

Basic propeties of tensors arithmetic

In [15]:
A = torch.arange(6,dtype=torch.float32).reshape(2,3)
B = A.clone()
A, A+B

(tensor([[0., 1., 2.],
         [3., 4., 5.]]), tensor([[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]))

In [16]:
A*B #matrix product랑은 다른 개념, Hadamard product라 부른다. elementwise product이다

tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])

In [18]:
a=2
X = torch.arange(24).reshape(2,3,4)
a + X, (a*X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]), torch.Size([2, 3, 4]))

Reduction

In [19]:
x = torch.arange(3, dtype=torch.float32)
x, x.sum() #vecotr sum

(tensor([0., 1., 2.]), tensor(3.))

In [23]:
A

tensor([[0., 1., 2.],
        [3., 4., 5.]])

In [22]:
A.shape, A.sum()

(torch.Size([2, 3]), tensor(15.))

In [25]:
A.shape, A.sum(axis=0).shape, A.sum(axis=0) #axis=0이니까 row가 사라지겠금

(torch.Size([2, 3]), torch.Size([3]), tensor([3., 5., 7.]))

In [26]:
A.shape, A.sum(axis=1).shape, A.sum(axis=1) #axis=1이니까 column이 사라지겠금

(torch.Size([2, 3]), torch.Size([2]), tensor([ 3., 12.]))

In [27]:
A.sum(axis=[0,1]) == A.sum()

tensor(True)

In [28]:
A.mean(), A.sum()/A.numel() #numel은 개수였지 기억해용

(tensor(2.5000), tensor(2.5000))

In [29]:
A.mean(axis=0), A.sum(axis=0)/A.shape[0]

(tensor([1.5000, 2.5000, 3.5000]), tensor([1.5000, 2.5000, 3.5000]))

Non-Reduction Sum