#2.1 Data Manipulation

In [33]:
import torch

Creating new tensor method : arange

In [34]:
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

total number of elements in tensor method : numel

In [35]:
x.numel()

12

the length along each axis
method : shape

In [36]:
x.shape

torch.Size([12])

chage shape method : reshape

In [37]:
X = x.reshape(3,4) # == x.reshape(-1,4) == x.reshape(3,-1)
X # 3*4 matrix

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [38]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [39]:
torch.ones(2,3,4)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

element randomly and independently method : randn

In [40]:
torch.randn(3,4) #들어가는건 dim

tensor([[ 1.7882, -0.3703, -0.8814,  0.0256],
        [ 0.4081, -2.9868, -0.6095,  0.9258],
        [-1.4957,  0.6718,  0.7990,  1.4699]])

construct tensors by supplying the exact values

In [41]:
torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [42]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [43]:
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]), tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [44]:
X[1,2] = 17
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 17.,  7.],
        [ 8.,  9., 10., 11.]])

In [45]:
X[:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

Elementwise operation들 중 
mathematical operations

In [46]:
torch.exp(X) #e^x에 x를 다 넣은거야

tensor([[162754.7969, 162754.7969, 162754.7969, 162754.7969],
        [162754.7969, 162754.7969, 162754.7969, 162754.7969],
        [  2980.9580,   8103.0840,  22026.4648,  59874.1406]])

In [47]:
x = torch.tensor([1.0,2,4,8])
y = torch.tensor([2,2,2,2])
x+y, x-y, x*y, x**y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([ 1.,  4., 16., 64.]))

In [48]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
torch.cat((X,Y),dim=0), torch.cat((X,Y),dim=1)
#dim=0은 axis 0을 기준으로, dim=1은 axis 1을 기준으로
#(3+3), (4+4) 꼴이 된거임

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [49]:
X == Y #element check

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [52]:
X < Y

tensor([[ True, False,  True, False],
        [False, False, False, False],
        [False, False, False, False]])

In [53]:
X > Y

tensor([[False, False, False, False],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

In [54]:
X.sum()

tensor(66.)

Broadcasting

In [57]:
a = torch.arange(3).reshape((3,1))
b = torch.arange(3).reshape((1,3))
a, b

(tensor([[0],
         [1],
         [2]]), tensor([[0, 1, 2]]))

In [58]:
a+b

tensor([[0, 1, 2],
        [1, 2, 3],
        [2, 3, 4]])

Saving Memory

In [27]:
before = id(Y) # id method는 메모리 주소를 알려주는 연산자 in python
Y = Y+X
id(Y) == before #allocating new memory 사실을 알 수 있음

False

In [29]:
Z = torch.zeros_like(Y)
print('id(Z):',id(Z))
Z[:] = X+Y #[:] = <expression>으로 in place update 가능
print('id(Z):',id(Z))

id(Z): 140435000235488
id(Z): 140435000235488


In [30]:
before = id(X)
X += Y #+= 연산자도 in place update가 가능
id(X) == before

True

Conversino to Other Python Objects

In [31]:
A = X.numpy()
B = torch.from_numpy(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [32]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)
#item method는 텐서에서 파이썬 스칼라 형식으로 바꿔주구만 in size-1 tensor

(tensor([3.5000]), 3.5, 3.5, 3)